# Generated by Django 5.2.5 on 2025-09-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_atual', models.IntegerField(default=1)),
                ('xp_total', models.IntegerField(default=0)),
                ('vidas_atual', models.IntegerField(default=10)),
                ('vidas_maxima', models.IntegerField(default=10)),
                ('ultima_recarga_vidas', models.DateTimeField(blank=True, null=True)),
                ('streak_atual', models.IntegerField(default=0)),
                ('melhor_streak', models.IntegerField(default=0)),
                ('posicao_ranking', models.IntegerField(blank=True, null=True)),
                ('conquistas_total', models.IntegerField(default=0)),
                ('ultima_conquista', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pyquest.usuario')),
            ],
        ),
    ]
