# Generated by Django 5.2.5 on 2025-09-14 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='max_vidas',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='total_conquistas',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_regeneracao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='progresso',
            name='xp_ganho',
            field=models.IntegerField(default=0),
        ),
    ]
