# Generated by Django 5.2.5 on 2025-09-14 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0006_perfil_max_vidas_perfil_total_conquistas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(blank=True, default='Ainda não escreveu nada.', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='lições',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('raro', 'Raro'), ('epico', 'Épico'), ('lendario', 'Lendário')], max_length=20)),
                ('categoria', models.CharField(choices=[('progresso', 'Progresso'), ('precisao', 'Precisão'), ('dominio', 'Domínio'), ('algoritmos', 'Algoritmos'), ('especial', 'Especial')], max_length=20)),
                ('icone', models.CharField(default='🏆', max_length=10)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
