# Generated by Django 5.2.5 on 2025-09-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0007_perfil_avatar_perfil_descricao_perfil_lições_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='lições',
            new_name='licoes',
        ),
    ]
