# Generated by Django 5.2.5 on 2025-09-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0008_rename_lições_perfil_licoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='categoria',
            field=models.CharField(choices=[('progresso', 'Progresso'), ('habilidade', 'Habilidade'), ('precisao', 'Precisão'), ('dominio', 'Domínio'), ('especial', 'Especial')], default='progresso', max_length=20),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='conquistas/'),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='raridade',
            field=models.CharField(choices=[('comum', 'Comum'), ('rara', 'Rara'), ('epica', 'Épica'), ('lendaria', 'Lendária')], default='comum', max_length=20),
        ),
    ]
