# Generated by Django 5.2.5 on 2025-09-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0011_aula_capitulo_atividade_aula_forum_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conquista',
            name='objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
