# Generated by Django 5.2.5 on 2025-09-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0014_hashtag_alter_post_autor_remove_post_hashtags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostaforum',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='respostaforum',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='RespostaForum',
        ),
    ]
