# Generated by Django 5.2.5 on 2025-10-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0018_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='contador',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='ultimo_uso',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='Pyquest.hashtag'),
        ),
    ]
