# Generated by Django 5.2.5 on 2025-10-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0019_auto_20251015_1146'),
    ]

    operations = [
    ]
