# Generated by Django 5.2.5 on 2025-10-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0019_hashtag_contador_hashtag_ultimo_uso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='contador',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='ultimo_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
