# Generated by Django 5.2.5 on 2025-10-15 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0020_auto_20251015_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='aula',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='dificuldade',
            field=models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='aula',
            name='questoes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aula',
            name='tempo_estimado',
            field=models.IntegerField(default=45),
        ),
    ]
