# Generated by Django 5.2.5 on 2025-10-19 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0024_alter_aula_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='titulo',
        ),
        migrations.AddField(
            model_name='aula',
            name='conteudo_pratico',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo Prático'),
        ),
        migrations.AddField(
            model_name='aula',
            name='conteudo_teorico',
            field=models.TextField(default='', verbose_name='Conteúdo Teórico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='descricao_breve',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Breve'),
        ),
        migrations.AddField(
            model_name='aula',
            name='tem_exercicios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='tem_teoria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='titulo_aula',
            field=models.CharField(default='', max_length=255, verbose_name='Título da Aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='titulo_pratica',
            field=models.CharField(default='Exercícios Práticos', max_length=255, verbose_name='Título do Conteúdo Prático'),
        ),
        migrations.AddField(
            model_name='aula',
            name='titulo_tarefa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título da Tarefa'),
        ),
        migrations.AddField(
            model_name='aula',
            name='titulo_teoria',
            field=models.CharField(default='Conteúdo Teórico', max_length=255, verbose_name='Título do Conteúdo Teórico'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='criado_por',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
