# Generated by Django 5.2.5 on 2025-10-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0025_remove_aula_conteudo_remove_aula_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='conteudo_teorico',
            field=models.TextField(blank=True, default='', verbose_name='Conteúdo Teórico'),
        ),
    ]
