# Generated by Django 5.2.5 on 2025-10-19 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0026_alter_aula_conteudo_teorico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='questoes',
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multiple-choice', 'Múltipla Escolha'), ('code', 'Programação'), ('fill-blank', 'Completar Lacunas')], max_length=20)),
                ('enunciado', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=10)),
                ('codigo_inicial', models.TextField(blank=True, null=True)),
                ('saida_esperada', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='Pyquest.aula')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='Pyquest.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='DicaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.IntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicas', to='Pyquest.questao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
