# Generated by Django 5.2.5 on 2025-10-19 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0027_remove_aula_questoes_questao_opcaoquestao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='conteudo_teorico',
        ),
        migrations.CreateModel(
            name='TopicoTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Tópico', max_length=255)),
                ('ordem', models.IntegerField(default=1)),
                ('conteudo', models.TextField(blank=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='Pyquest.aula')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
