# Generated by Django 5.2.5 on 2025-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0028_remove_aula_conteudo_teorico_topicoteorico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='dificuldade',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='dificuldade',
            field=models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
