# Generated by Django 5.2.5 on 2025-10-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0031_aulaconcluida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='tempo_estimado',
        ),
        migrations.AddField(
            model_name='aula',
            name='tempo_pratica',
            field=models.IntegerField(default=15, verbose_name='Tempo Estimado para Prática (minutos)'),
        ),
        migrations.AddField(
            model_name='aula',
            name='tempo_teoria',
            field=models.IntegerField(default=30, verbose_name='Tempo Estimado para Teoria (minutos)'),
        ),
        migrations.AddField(
            model_name='aula',
            name='tempo_total',
            field=models.IntegerField(default=45, verbose_name='Tempo Total Estimado (minutos)'),
        ),
        migrations.AddField(
            model_name='aula',
            name='xp_pratica',
            field=models.IntegerField(default=0, verbose_name='XP Total das Questões Práticas'),
        ),
        migrations.AddField(
            model_name='aula',
            name='xp_teoria',
            field=models.IntegerField(default=30, verbose_name='XP por Concluir Teoria'),
        ),
    ]
