# Generated by Django 5.2.5 on 2025-10-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0032_remove_aula_tempo_estimado_aula_tempo_pratica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='contador',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='ultimo_uso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='Pyquest.hashtag'),
        ),
    ]
