# Generated by Django 5.2.5 on 2025-10-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0033_hashtag_contador_hashtag_ultimo_uso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='conteudo_pratico',
            field=models.TextField(default='Lista de exercícios para praticar os conceitos aprendidos.', verbose_name='Descrição da Lista de Exercícios'),
        ),
    ]
