# Generated by Django 5.2.5 on 2025-10-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0034_alter_aula_conteudo_pratico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aulaconcluida',
            old_name='xp_ganho',
            new_name='xp_pratica_ganho',
        ),
        migrations.RemoveField(
            model_name='aulaconcluida',
            name='data_conclusao',
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='data_conclusao_pratica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='data_conclusao_teoria',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='pratica_concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='teoria_concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='xp_teoria_ganho',
            field=models.IntegerField(default=0),
        ),
    ]
