# Generated by Django 5.2.5 on 2025-10-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0035_rename_xp_ganho_aulaconcluida_xp_pratica_ganho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulaconcluida',
            name='revisao_feita_pratica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='revisao_feita_teoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='xp_revisao_ganho_pratica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aulaconcluida',
            name='xp_revisao_ganho_teoria',
            field=models.IntegerField(default=0),
        ),
    ]
