# Generated by Django 5.2.5 on 2025-10-29 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0036_aulaconcluida_revisao_feita_pratica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conquista',
            options={'ordering': ['categoria', 'ordem', 'raridade']},
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='conquista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conquista',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conquista',
            name='multiplos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conquista',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conquista',
            name='progressivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conquista',
            name='tipo_evento',
            field=models.CharField(choices=[('xp_total', 'XP Total Alcançado'), ('nivel_atingido', 'Nível Alcançado'), ('aulas_concluidas', 'Aulas Concluídas'), ('modulos_concluidos', 'Módulos Concluídos'), ('sequencia_dias', 'Sequência de Dias'), ('questoes_corretas', 'Questões Corretas'), ('tempo_estudo', 'Tempo de Estudo'), ('postagens_forum', 'Postagens no Fórum'), ('comentarios', 'Comentários Feitos'), ('likes_recebidos', 'Likes Recebidos'), ('conquistas_desbloqueadas', 'Conquistas Desbloqueadas')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conquista',
            name='valor_requerido',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='conquista',
            name='xp_recompensa',
            field=models.IntegerField(default=10),
        ),
    ]
