# Generated by Django 5.2.5 on 2025-11-02 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0037_alter_conquista_options_remove_conquista_objetivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultima_atualizacao_vidas',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TempoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('teoria', 'Teoria'), ('pratica', 'Prática')], max_length=10)),
                ('tempo_segundos', models.IntegerField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pyquest.aula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aula', 'tipo', 'data')},
            },
        ),
        migrations.CreateModel(
            name='TentativaPratica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidas_usadas', models.IntegerField(default=0)),
                ('vidas_restantes', models.IntegerField(default=3)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('concluida', models.BooleanField(default=False)),
                ('xp_ganho', models.IntegerField(default=0)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pyquest.aula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'aula')},
            },
        ),
    ]
