# Generated by Django 5.2.5 on 2025-11-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0038_perfil_ultima_atualizacao_vidas_tempoestudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tempo_total_estudo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='xp_hoje',
            field=models.IntegerField(default=0),
        ),
    ]
