# Generated by Django 5.2.5 on 2025-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0039_perfil_tempo_total_estudo_perfil_xp_hoje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='xp_hoje',
            new_name='sequencia_maxima',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ultima_atualizacao_vidas',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
