# Generated by Django 5.2.5 on 2025-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0040_rename_xp_hoje_perfil_sequencia_maxima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='sequencia_maxima',
            new_name='xp_hoje',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ultima_atividade',
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_atualizacao_vidas',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
