# Generated by Django 5.2.5 on 2025-11-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0041_rename_sequencia_maxima_perfil_xp_hoje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='respostas_corretas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de respostas corretas para questões do tipo fill-blank'),
        ),
    ]
