# Generated by Django 5.2.5 on 2025-11-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0042_questao_respostas_corretas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conquista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['ordem'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.RemoveField(
            model_name='aulaconcluida',
            name='revisao_feita_pratica',
        ),
        migrations.RemoveField(
            model_name='aulaconcluida',
            name='revisao_feita_teoria',
        ),
        migrations.RemoveField(
            model_name='aulaconcluida',
            name='xp_revisao_ganho_pratica',
        ),
        migrations.RemoveField(
            model_name='aulaconcluida',
            name='xp_revisao_ganho_teoria',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='multiplos',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='progressivo',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='tipo_evento',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='valor_requerido',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='xp_recompensa',
        ),
        migrations.AddField(
            model_name='conquista',
            name='objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sequencia_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
