# Generated by Django 5.2.5 on 2025-11-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0044_alter_conquista_options_alter_questao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['ordem'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='sequencia_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
