# Generated by Django 5.2.5 on 2025-11-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0045_alter_questao_options_perfil_sequencia_maxima_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('teoria', 'Teoria'), ('pratica', 'Prática')], max_length=10)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('tempo_total', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pyquest.aula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
