# Generated by Django 5.2.5 on 2025-11-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0046_sessaoestudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='acertos_seguidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='precisao_geral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='recorde_acertos',
            field=models.IntegerField(default=0),
        ),
    ]
