# Generated by Django 5.2.5 on 2025-11-15 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0048_tempoestudodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ja_fez_atividade_hoje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_verificacao_diaria',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
