# Generated by Django 5.2.5 on 2025-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0049_perfil_ja_fez_atividade_hoje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='background_image',
            field=models.ImageField(blank=True, default='backgrounds/default-bg.jpg', null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo'),
        ),
    ]
