# Generated by Django 5.2.5 on 2025-11-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0050_perfil_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='acertos_seguidos',
            field=models.IntegerField(default=0, help_text='Sequência atual de acertos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='conquistas',
            field=models.IntegerField(default=0, help_text='Número de conquistas desbloqueadas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='licoes',
            field=models.IntegerField(default=0, help_text='Número de lições concluídas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='max_vidas',
            field=models.IntegerField(default=10, help_text='Número máximo de vidas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel',
            field=models.IntegerField(default=1, help_text='Nível atual do usuário'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='precisao_geral',
            field=models.IntegerField(default=0, help_text='Precisão geral em porcentagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='recorde_acertos',
            field=models.IntegerField(default=0, help_text='Maior sequência de acertos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sequencia',
            field=models.IntegerField(default=0, help_text='Sequência atual de dias estudando'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sequencia_maxima',
            field=models.IntegerField(default=0, help_text='Maior sequência já alcançada'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tempo_total_estudo',
            field=models.IntegerField(default=0, help_text='Tempo total de estudo em segundos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='total_conquistas',
            field=models.IntegerField(default=50, help_text='Total de conquistas disponíveis'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, help_text='Última atividade registrada', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vidas',
            field=models.IntegerField(default=10, help_text='Vidas atuais'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='xp',
            field=models.IntegerField(default=0, help_text='Pontos de experiência acumulados'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='xp_hoje',
            field=models.IntegerField(default=0, help_text='XP ganho hoje'),
        ),
    ]
