# Generated by Django 5.2.5 on 2025-11-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0051_alter_perfil_acertos_seguidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='acertos_seguidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='conquistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='licoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='max_vidas',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='precisao_geral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='recorde_acertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sequencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sequencia_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tempo_total_estudo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='total_conquistas',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ultima_atividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='vidas',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='xp_hoje',
            field=models.IntegerField(default=0),
        ),
    ]
