# Generated by Django 5.2.5 on 2025-09-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
