# Generated by Django 5.2.5 on 2025-09-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pyquest', '0009_alter_conquista_categoria_alter_conquista_icone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
